sudo: false

os:
  - linux

env:
  matrix:
    - COVERALLS_REPO_TOKEN=qPx1suoyo7HD8uotEhbOrfuk1EJYcOo0N

language: node_js

cache:
  yarn: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - node_modules
    - test/tasks/tmp/elm-stuff/build-artifacts
    - sysconfcpus

install:
  - nvm install
  - yarn

after_success:
  yarn run coverage
