version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4-stretch@sha256:a7185e5ff3093e3933f922a7e9c3211f69cd91943341a4153122055b74f5e323
    steps:
      - checkout
      - run:
          name: Setup Machine
          command: |
            echo 'export PATH=${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin' >> $BASH_ENV;
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Sign in to Github
          command: |
            git config --global user.email "farismmk@gmail.com";
            git config --global user.name "Faris Mustafa"
      - run:
          name: Run Yarn
          command: yarn
      - run:
          name: Build Packages
          command: yarn build
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
      - deploy:
          name: Deploying
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              npm run deploy:next
              npm run deploy:ghpages next
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy:stable
              npm run deploy:ghpages
            fi
